/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * reliableserial.h.
 */

public class RelConstants  {
    public static final short ACK_TIMEOUT = 250;
}
